### PR TITLE
Fix memleak

### LINKED ISSUE #348: possible memory leak
there seems to be a memory leak when scrolling the mouse wheel. at first i though it could be related to going in and out of  territory mode, however, it seems that the mere action of scrolling makes memory go up. i though it might just be the lazy GC not working, but even after forcing a garbage collection the memory usage didnt change.

browser: firefox
branch: master (production, solaris.games)

steps to reproduce:
- open a game map
- watch RAM usage closely
- scroll in and out and watch memory rise
- force a garbage collection on the browser( nothing changes )
- close game tab
- force garbage collection again( now memory is freed )

### PR DESCRIPTION
**Pull request by Kurtzmusch**
this branch does 2 things:
- fixes the resource leak by calling texture.destroy() everytime draw is called for some text: drawGarrison, drawResources, etc
- avoids calling the draw methods and calls updateVisibility() instead, since redrawing objects every time that something gets selected is wastefull. togling container.visible is enough

closes #348

### CODE REVIEW

File: client/src/game/map.js [hunk 1]
```diff
@@ -332,15 +332,15 @@ class Map extends EventEmitter {
...
+        s.updateVisibility() // Should be fine to pass in false for force
       })
   }
 
   unselectAllCarriers () {
     this.carriers
       .forEach(c => {
         c.isSelected = false
-        c.drawActive()
+        //c.updateVisibility()
```
Comment (mike-eason) [inline client/src/game/map.js:343]: Is this meant to be commented out?

File: client/src/game/map.js [hunk 2]
```diff
@@ -366,7 +366,7 @@ class Map extends EventEmitter {
           c.isSelected = false
         }
 
-        c.drawActive(false) // Should be fine to pass in false for the force param
+        //c.updateVisibility()
```
Comment (mike-eason) [inline client/src/game/map.js:369]: Is this meant to be commented out?

File: client/src/game/star.js [hunk 3]
```diff
@@ -107,14 +95,13 @@ class Star extends EventEmitter {
...
 
-    this.container.hitArea = new PIXI.Circle(this.data.location.x, this.data.location.y, 15)
   }
 
   drawSpecialist () {
     if (!this.hasSpecialist()) {
       return
     }
-    
+    //FIXME potential resource leak, should not create a new sprite every time
```
Comment (mike-eason) [inline client/src/game/star.js:104]: We should raise another issue for this.

**Review by mike-eason — CHANGES_REQUESTED** [review]
